name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t gradio-app -f CI-CD/Dockerfile CI-CD

      - name: Test Docker container
        run: |
          docker run -d -p 3000:3000 --env GRADIO_SERVER_NAME=0.0.0.0 --env GRADIO_SERVER_PORT=3000 gradio-app
          sleep 8
          curl -I http://localhost:3000 | head -n 1

      - name: Deploy to Vercel
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd CI-CD
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}